# Jekyll configuration

name: Kevin Lubick
description: <h1>Hello!</h1><p>My name is Kevin Lubick.  I work at Google on <a href="https://skia.org">Skia</a>.  I have done research in <a href="http://research.csc.ncsu.edu/dlf/">The Developer Liberation Front</a>, and done zero-G research aboard NASA's G-Force one with <a href="https://www.carthage.edu/physics/opportunities/space-sciences/">Carthage College Space Sciences</a>.</p>

# url is currently only used only for the RSS feed in feed.xml
url: http://kevinlubick.com

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'kjlubick'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: false

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE', 'wip', 'old']

gems:
  - jekyll-sitemap
